services:
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kirbyotd
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        VITE_API_URL: http://192.168.0.158:3000 # Use Domain name if exists, otherwise use public IP
    container_name: kirbyotd_frontend
    ports:
      - 80:8080
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: kirbyotd_backend
    secrets:
      - db-password
    environment:
      - DB_HOSTNAME="db" # Should usually always be db for this compose file
      - DB_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3000:3000
volumes:
  db-data:
secrets:
  db-password:
    file: server/password.txt
