services:
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kirbyotd
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - TZ=America/Chicago
    ports:
      - 5432:5432
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        VITE_API_URL: https://mathisfun.unibutton.com/api # Use Domain name if exists, otherwise use public IP
    container_name: kirbyotd_frontend
    ports:
      - 8080:8080
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: kirbyotd_backend
    secrets:
      - db-password
    environment:
      - DB_HOSTNAME=db # Should usually always be db for this compose file
      - DB_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3000:3000
  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db-data:
  caddy_data:
  caddy_config:
secrets:
  db-password:
    file: server/password.txt
